# Generated by Django 5.2.15 on 2026-06-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otype', models.CharField(blank=True, choices=[('article', 'Article'), ('feed:urls', 'Feed URLs'), ('feed:entries', 'Feed Entries')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('domains', models.ManyToManyField(blank=True, to='domains.domain')),
            ],
        ),
    ]
