# Generated by Django 5.2.15 on 2026-06-06 17:24

import django.contrib.postgres.fields
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=100)),
                ('middle', models.CharField(blank=True, max_length=100)),
                ('last', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=100)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('sentiment', models.JSONField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedlin', 'LinkedIn'), ('google+', 'Google+'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('flickr', 'Flickr'), ('foursquare', 'Foursquare'), ('kik', 'Kik'), ('yikyak', 'Yik Yah'), ('shots', 'Shots'), ('periscope', 'Periscope')], max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=250)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='people.person')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
