# Generated by Django 5.2.16 on 2026-07-17 07:29

from django.db import migrations, models


def fix_linkedin_typo(apps, schema_editor):
    SocialAccount = apps.get_model('people', 'SocialAccount')
    SocialAccount.objects.filter(type='linkedlin').update(type='linkedin')


def restore_linkedin_typo(apps, schema_editor):
    SocialAccount = apps.get_model('people', 'SocialAccount')
    SocialAccount.objects.filter(type='linkedin').update(type='linkedlin')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_linkedin_typo, restore_linkedin_typo),
        migrations.AlterField(
            model_name='socialaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('google+', 'Google+'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('flickr', 'Flickr'), ('foursquare', 'Foursquare'), ('kik', 'Kik'), ('yikyak', 'Yik Yak'), ('shots', 'Shots'), ('periscope', 'Periscope')], max_length=20, null=True),
        ),
    ]
