# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=filer.fields.image.FilerImageField(default="", on_delete=django.db.models.deletion.CASCADE, related_name='people', to=b'filer.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='people.Person'),
        ),
    ]
