# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170424_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='SocialAccount',
        ),
    ]
