# Generated by Django 5.2.16 on 2026-07-17 07:29

from django.db import migrations, models
from django.utils.text import slugify


def dedupe_article_slugs(apps, schema_editor):
    """Backfill and de-duplicate slugs before the unique constraint lands.

    The old Article.save() set slug=slugify(title) with no de-duplication, so
    articles sharing a title share a slug, and non-Latin titles all slugified
    to ''.
    """
    Article = apps.get_model('news', 'Article')
    seen = set()
    for article in Article.objects.order_by('pk').iterator():
        slug = article.slug or slugify(article.title)[:240] or f'article-{article.pk}'
        base = slug[:240]
        suffix = 2
        while slug in seen:
            slug = f'{base}-{suffix}'
            suffix += 1
        seen.add(slug)
        if slug != article.slug:
            article.slug = slug
            article.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_article_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
