# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('msg', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.CharField(choices=[('http', 'http'), ('http', 'https')], default='https', max_length=5)),
                ('sub', models.CharField(blank=True, max_length=30)),
                ('domain', models.CharField(default='www', max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=30)),
                ('favicon', models.URLField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='crawl',
            name='domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
    ]
