# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 23:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('msg', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.CharField(blank=True, choices=[('http', 'http'), ('http', 'https')], default='https', max_length=5, null=True)),
                ('sub', models.CharField(blank=True, max_length=30, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('favicon', models.URLField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
                ('sentiment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='domains.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='crawl',
            name='domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
    ]
