# Generated by Django 5.2.15 on 2026-06-06 17:24

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.CharField(blank=True, choices=[('http', 'http'), ('https', 'https')], default='https', max_length=5, null=True)),
                ('sub', models.CharField(blank=True, max_length=30, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('favicon', models.URLField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('sentiment', models.JSONField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
                ('writers', models.ManyToManyField(blank=True, to='people.person')),
            ],
        ),
    ]
