# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='slug',
        ),
    ]
