# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_remove_domain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='domain',
            name='favicon',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='proto',
            field=models.CharField(blank=True, choices=[('http', 'http'), ('http', 'https')], default='https', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='sub',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
