# Generated by Django 5.2.15 on 2026-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(default='wss://open-data.api.satori.com', max_length=60)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('appkey', models.CharField(blank=True, max_length=130, null=True)),
            ],
        ),
    ]
