# Generated by Django 5.2.16 on 2026-07-17 07:29

from django.db import migrations, models
from django.utils.text import slugify


def dedupe_place_slugs(apps, schema_editor):
    """Backfill and de-duplicate slugs before the unique constraint lands."""
    Place = apps.get_model('places', 'Place')
    seen = set()
    for place in Place.objects.order_by('pk').iterator():
        slug = place.slug or slugify(place.name)[:40] or f'place-{place.pk}'
        base = slug[:40]
        suffix = 2
        while slug in seen:
            slug = f'{base}-{suffix}'
            suffix += 1
        seen.add(slug)
        if slug != place.slug:
            place.slug = slug
            place.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_place_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
